variable "region" {
  default = "us-east-1"
}

variable "instance_type" {
  default = "t2.micro"
}

variable "key_name" {
  description = "Existing AWS key pair name"
}

variable "ami_id" {
  description = "Optional AMI override. Leave empty to use latest Amazon Linux 2023 via SSM."
  default     = ""
}

variable "repo_url" {
  description = "GitHub repository URL"
  type        = string
}
variable "dockerfile_content" {
  description = "Dockerfile generated by Claude"
  type        = string
}

variable "app_port" {
  description = "Container port to expose"
  type        = string
  default     = "3000"
}